[project]
name = "splatviz"
version = "0.1.0"
requires-python = ">=3.10,<3.11"
dependencies = [
  "setuptools",
  "ninja",

  "click",
  "glfw",
  "gputil",
  "imagecodecs[all]>=2025.3.30",
  "imageio[ffmpeg]",
  "imgui-bundle==1.5.2",

  "numpy",
  "opencv-python",
  "pandas>=2.3.3",
  "pillow",
  "plyfile",
  "pynvml>=13.0.1",
  "pyopengl",
  "pyyaml",
  "requests>=2.33.1",
]

[project.optional-dependencies]
cu118 = ["torch"]
cu126 = ["torch"]
cu128 = ["torch"]
cu130 = ["torch"]

[tool.uv]
package = false
conflicts = [
  [
    { extra = "cu118" },
    { extra = "cu126" },
    { extra = "cu128" },
    { extra = "cu130" },
  ],
]


[tool.uv.sources]
torch = [
  { index = "pytorch-cu118", extra = "cu118" },
  { index = "pytorch-cu126", extra = "cu126" },
  { index = "pytorch-cu128", extra = "cu128" },
  { index = "pytorch-cu130", extra = "cu130" },
]

[[tool.uv.index]]
name = "pytorch-cu118"
url = "https://download.pytorch.org/whl/cu118"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true