active_sh_degree: 3
attributes:
- method: jpeg-xl
  name: _xyz
  normalize: true
  params:
    level: 101
  quantize: 14
- method: jpeg-xl
  name: _features_dc
  normalize: true
  params:
    level: 100
- method: jpeg-xl
  name: _features_rest
  normalize: true
  params:
    level: 101
  quantize: 5
- contract: false
  method: jpeg-xl
  name: _scaling
  normalize: false
  params:
    level: 101
  quantize: 6
- method: jpeg-xl
  name: _rotation
  normalize: true
  params:
    level: 101
  quantize: 6
- contract: false
  method: jpeg-xl
  name: _opacity
  normalize: true
  params:
    level: 101
  quantize: 6
disable_xyz_log_activation: false
max_sh_degree: 3
name: jxl_quant_sh
