from imgui_bundle import imgui


def _value(enum_value):
    return enum_value.value


def _optional_value(enum_cls, name, default=0):
    enum_value = getattr(enum_cls, name, None)
    return default if enum_value is None else enum_value.value


# Condition constants.
NONE = _value(imgui.Cond_.none)
ALWAYS = _value(imgui.Cond_.always)
ONCE = _value(imgui.Cond_.once)
FIRST_USE_EVER = _value(imgui.Cond_.first_use_ever)
APPEARING = _value(imgui.Cond_.appearing)

# Window flags.
WINDOW_NONE = _value(imgui.WindowFlags_.none)
WINDOW_NO_TITLE_BAR = _value(imgui.WindowFlags_.no_title_bar)
WINDOW_NO_RESIZE = _value(imgui.WindowFlags_.no_resize)
WINDOW_NO_MOVE = _value(imgui.WindowFlags_.no_move)
WINDOW_NO_SCROLLBAR = _value(imgui.WindowFlags_.no_scrollbar)
WINDOW_NO_SCROLL_WITH_MOUSE = _value(imgui.WindowFlags_.no_scroll_with_mouse)
WINDOW_NO_COLLAPSE = _value(imgui.WindowFlags_.no_collapse)
WINDOW_ALWAYS_AUTO_RESIZE = _value(imgui.WindowFlags_.always_auto_resize)
WINDOW_NO_BACKGROUND = _value(imgui.WindowFlags_.no_background)
WINDOW_NO_SAVED_SETTINGS = _value(imgui.WindowFlags_.no_saved_settings)
WINDOW_NO_MOUSE_INPUTS = _value(imgui.WindowFlags_.no_mouse_inputs)
WINDOW_MENU_BAR = _value(imgui.WindowFlags_.menu_bar)
WINDOW_HORIZONTAL_SCROLLING_BAR = _value(imgui.WindowFlags_.horizontal_scrollbar)
WINDOW_NO_FOCUS_ON_APPEARING = _value(imgui.WindowFlags_.no_focus_on_appearing)
WINDOW_NO_BRING_TO_FRONT_ON_FOCUS = _value(imgui.WindowFlags_.no_bring_to_front_on_focus)
WINDOW_ALWAYS_VERTICAL_SCROLLBAR = _value(imgui.WindowFlags_.always_vertical_scrollbar)
WINDOW_ALWAYS_HORIZONTAL_SCROLLBAR = _value(imgui.WindowFlags_.always_horizontal_scrollbar)
WINDOW_ALWAYS_USE_WINDOW_PADDING = _optional_value(imgui.WindowFlags_, "always_use_window_padding")
WINDOW_NO_NAV_INPUTS = _value(imgui.WindowFlags_.no_nav_inputs)
WINDOW_NO_NAV_FOCUS = _value(imgui.WindowFlags_.no_nav_focus)
WINDOW_UNSAVED_DOCUMENT = _value(imgui.WindowFlags_.unsaved_document)
WINDOW_NO_NAV = _value(imgui.WindowFlags_.no_nav)
WINDOW_NO_DECORATION = _value(imgui.WindowFlags_.no_decoration)
WINDOW_NO_INPUTS = _value(imgui.WindowFlags_.no_inputs)

# Tree node flags.
TREE_NODE_NONE = _value(imgui.TreeNodeFlags_.none)
TREE_NODE_SELECTED = _value(imgui.TreeNodeFlags_.selected)
TREE_NODE_FRAMED = _value(imgui.TreeNodeFlags_.framed)
TREE_NODE_ALLOW_ITEM_OVERLAP = _value(imgui.TreeNodeFlags_.allow_overlap)
TREE_NODE_NO_TREE_PUSH_ON_OPEN = _value(imgui.TreeNodeFlags_.no_tree_push_on_open)
TREE_NODE_NO_AUTO_OPEN_ON_LOG = _value(imgui.TreeNodeFlags_.no_auto_open_on_log)
TREE_NODE_DEFAULT_OPEN = _value(imgui.TreeNodeFlags_.default_open)
TREE_NODE_OPEN_ON_DOUBLE_CLICK = _value(imgui.TreeNodeFlags_.open_on_double_click)
TREE_NODE_OPEN_ON_ARROW = _value(imgui.TreeNodeFlags_.open_on_arrow)
TREE_NODE_LEAF = _value(imgui.TreeNodeFlags_.leaf)
TREE_NODE_BULLET = _value(imgui.TreeNodeFlags_.bullet)
TREE_NODE_FRAME_PADDING = _value(imgui.TreeNodeFlags_.frame_padding)
TREE_NODE_SPAN_AVAILABLE_WIDTH = _value(imgui.TreeNodeFlags_.span_avail_width)
TREE_NODE_SPAN_FULL_WIDTH = _value(imgui.TreeNodeFlags_.span_full_width)
TREE_NODE_NAV_LEFT_JUPS_BACK_HERE = _value(imgui.TreeNodeFlags_.nav_left_jumps_back_here)
TREE_NODE_COLLAPSING_HEADER = _value(imgui.TreeNodeFlags_.collapsing_header)

# Colors.
COLOR_TEXT = _value(imgui.Col_.text)
COLOR_TEXT_DISABLED = _value(imgui.Col_.text_disabled)
COLOR_WINDOW_BACKGROUND = _value(imgui.Col_.window_bg)
COLOR_CHILD_BACKGROUND = _value(imgui.Col_.child_bg)
COLOR_POPUP_BACKGROUND = _value(imgui.Col_.popup_bg)
COLOR_BORDER = _value(imgui.Col_.border)
COLOR_BORDER_SHADOW = _value(imgui.Col_.border_shadow)
COLOR_FRAME_BACKGROUND = _value(imgui.Col_.frame_bg)
COLOR_FRAME_BACKGROUND_HOVERED = _value(imgui.Col_.frame_bg_hovered)
COLOR_FRAME_BACKGROUND_ACTIVE = _value(imgui.Col_.frame_bg_active)
COLOR_TITLE_BACKGROUND = _value(imgui.Col_.title_bg)
COLOR_TITLE_BACKGROUND_ACTIVE = _value(imgui.Col_.title_bg_active)
COLOR_TITLE_BACKGROUND_COLLAPSED = _value(imgui.Col_.title_bg_collapsed)
COLOR_MENUBAR_BACKGROUND = _value(imgui.Col_.menu_bar_bg)
COLOR_SCROLLBAR_BACKGROUND = _value(imgui.Col_.scrollbar_bg)
COLOR_SCROLLBAR_GRAB = _value(imgui.Col_.scrollbar_grab)
COLOR_SCROLLBAR_GRAB_HOVERED = _value(imgui.Col_.scrollbar_grab_hovered)
COLOR_SCROLLBAR_GRAB_ACTIVE = _value(imgui.Col_.scrollbar_grab_active)
COLOR_CHECK_MARK = _value(imgui.Col_.check_mark)
COLOR_SLIDER_GRAB = _value(imgui.Col_.slider_grab)
COLOR_SLIDER_GRAB_ACTIVE = _value(imgui.Col_.slider_grab_active)
COLOR_BUTTON = _value(imgui.Col_.button)
COLOR_BUTTON_HOVERED = _value(imgui.Col_.button_hovered)
COLOR_BUTTON_ACTIVE = _value(imgui.Col_.button_active)
COLOR_HEADER = _value(imgui.Col_.header)
COLOR_HEADER_HOVERED = _value(imgui.Col_.header_hovered)
COLOR_HEADER_ACTIVE = _value(imgui.Col_.header_active)
COLOR_SEPARATOR = _value(imgui.Col_.separator)
COLOR_SEPARATOR_HOVERED = _value(imgui.Col_.separator_hovered)
COLOR_SEPARATOR_ACTIVE = _value(imgui.Col_.separator_active)
COLOR_RESIZE_GRIP = _value(imgui.Col_.resize_grip)
COLOR_RESIZE_GRIP_HOVERED = _value(imgui.Col_.resize_grip_hovered)
COLOR_RESIZE_GRIP_ACTIVE = _value(imgui.Col_.resize_grip_active)
COLOR_TAB = _value(imgui.Col_.tab)
COLOR_TAB_HOVERED = _value(imgui.Col_.tab_hovered)
COLOR_TAB_ACTIVE = _value(imgui.Col_.tab_selected)
COLOR_TAB_UNFOCUSED = _value(imgui.Col_.tab_dimmed)
COLOR_TAB_UNFOCUSED_ACTIVE = _value(imgui.Col_.tab_dimmed_selected)
COLOR_PLOT_LINES = _value(imgui.Col_.plot_lines)
COLOR_PLOT_LINES_HOVERED = _value(imgui.Col_.plot_lines_hovered)
COLOR_PLOT_HISTOGRAM = _value(imgui.Col_.plot_histogram)
COLOR_PLOT_HISTOGRAM_HOVERED = _value(imgui.Col_.plot_histogram_hovered)
COLOR_TEXT_SELECTED_BACKGROUND = _value(imgui.Col_.text_selected_bg)
COLOR_DRAG_DROP_TARGET = _value(imgui.Col_.drag_drop_target)
COLOR_NAV_HIGHLIGHT = _value(imgui.Col_.nav_highlight)
COLOR_NAV_WINDOWING_HIGHLIGHT = _value(imgui.Col_.nav_windowing_highlight)
COLOR_NAV_WINDOWING_DIM_BACKGROUND = _value(imgui.Col_.nav_windowing_dim_bg)
COLOR_MODAL_WINDOW_DIM_BACKGROUND = _value(imgui.Col_.modal_window_dim_bg)
COLOR_COUNT = _value(imgui.Col_.count)
